name: Business Success
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74866
title: Ideas and Articles to help you achieve business success
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171516'
    - '#ffffff'
    - '#b8b8b8'
    - '#8a8a8a'
    - '#5c5c5c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
