name: Business Success
favicon: null
layout_spectrum: 0.5383155082818121
typography_spectrum: 0.0748103957157582
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.038492337334901094
  lightness: 0.4478602858725935
  saturation: 0.031678115483373404
  rhythmicContrast: 0.754116281401366
purpose: []
